"""Default manifest for the final work-review deck (with-cursor iteration)."""

from __future__ import annotations

from typing import Any

DEFAULT_FINAL_REVIEW_MANIFEST: dict[str, Any] = {
    "manifest_version": 1,
    "deck_title": "Autonomous Satellite Control — Full Work Review",
    "deck_subtitle": "Semester project · cloud-aware learned pointing in simulation",
    "slides": [
        {
            "id": "M01",
            "section": "main",
            "title": "Opening — rainforest EO under clouds",
            "status": "draft",
            "bullets": [
                "Climate / environmental monitoring: rainforest regions are often cloud-covered.",
                "Useful imagery requires timing and pointing — not blind overflight shuttering.",
                "Autonomous Satellite Control — semester project review.",
            ],
            "notes": "User choice: hook-first opening (slide 1-B).",
        },
        {
            "id": "M02",
            "section": "main",
            "title": "Agenda",
            "status": "draft",
            "bullets": [
                "Research question",
                "How we built the experiment",
                "What we experimented on",
                "Results & evidence",
                "Conclusion & next steps",
            ],
            "notes": "User choice: linear agenda (slide 2-A).",
        },
        {
            "id": "M03",
            "section": "main",
            "title": "Why this work is needed",
            "status": "draft",
            "bullets": [
                "Earth observation for climate science depends on clear, high-value captures.",
                "Rainforest targets are frequently occluded by moving cloud fields.",
                "Scientists lose observation yield when onboard logic cannot exploit live vision.",
            ],
            "notes": "User choice: climate / rainforest framing (slide 3-A).",
        },
        {
            "id": "M04",
            "section": "main",
            "title": "Shortcomings of the deterministic baseline",
            "status": "draft",
            "bullets": [
                "Notebook 07 baseline: fixed nadir attitude + pre-planned shutter on every target vector.",
                "Cannot distinguish cloud-blocked vs clear views — shutters blindly.",
                "Wastes onboard memory / downlink budget on low-value frames.",
            ],
            "notes": "User choice: nb07 baseline (slide 4-A).",
        },
        {
            "id": "M05",
            "section": "main",
            "title": "Primary research question",
            "status": "draft",
            "bullets": [
                "Can a cloud-aware learned policy outperform the deterministic baseline on observation value?",
                "Observation value = successful captures weighted by quality, coverage, and target novelty.",
                "Comparison on matched environment setups (same clouds, altitude, target layout per episode).",
            ],
            "notes": "User choice: primary question (slide 5-A).",
        },
        {
            "id": "M06",
            "section": "main",
            "title": "Scope & non-goals",
            "status": "draft",
            "bullets": [
                "In scope: single-satellite 2D overflight simulation with cloud-aware sensing.",
                "Simplifications: 2D attitude, single pass, simulated vision — not flight hardware.",
                "Non-goals: multi-satellite ops, 3D deliverable, SOTA RL benchmark chasing.",
            ],
            "notes": "User choice: scope slide (slide 6-B).",
        },
        {
            "id": "M07",
            "section": "main",
            "title": "End-to-end experiment architecture",
            "status": "draft",
            "bullets": [
                "Gym env → agent (SAC / MPO) → canonical simulation rollout → reward signals.",
                "One episode = one SimulationStateSeries (train = eval = render).",
                "Artifacts: config.json, episodes.csv, telemetry, learning plots, MP4 exports.",
            ],
            "notes": "User choice: diagram slide (slide 7-C). Add diagram in PowerPoint.",
        },
        {
            "id": "M07b",
            "section": "main",
            "title": "Flowchart — ML agents (SAC & MPO)",
            "status": "ready",
            "image": "diagrams/ml_agents_flow.png",
            "bullets": [
                "Shared encoder + Actor/Critic; per-step store → ReplayBuffer.",
                "SAC: sparse reward, fixed entropy α · MPO: dense reward, η KL trust region.",
            ],
            "notes": "Editable source: diagrams/ml_agents_flow.mmd · regenerate: python .cursor/tools/presentation/presentation_pptx.py diagrams",
        },
        {
            "id": "M07c",
            "section": "main",
            "title": "Flowchart — simulation kernel (high level)",
            "status": "ready",
            "image": "diagrams/simulation_kernel_flow.png",
            "bullets": [
                "build_stepper from EnvironmentSetup; one SimulationStateSeries per episode.",
                "Each step: control → dynamics → SensorKernel rays → RewardKernel.",
            ],
            "notes": "Editable source: diagrams/simulation_kernel_flow.mmd",
        },
        {
            "id": "M08",
            "section": "main",
            "title": "ML integration",
            "status": "draft",
            "bullets": [
                "Agents: SAC (sparse reward) and MPO (dense capture credit).",
                "Observations: modular encoder over camera / target features.",
                "Actions: reaction-wheel torque (Ref0) or nadir-relative vector reference (Exp 4).",
            ],
            "notes": "User choice: agents + encoder (slide 8-A).",
        },
        {
            "id": "M09",
            "section": "main",
            "title": "Mission scenario",
            "status": "draft",
            "bullets": [
                "Single overflight window per episode (incl. pre-maneuver segment).",
                "~50 coordinate-defined targets along an observation stripe.",
                "Random altitude draw per episode → GSD / geometry generalization.",
            ],
            "notes": "User choice: mission scenario only (slide 9-A). Safety on M12; setup on M11.",
        },
        {
            "id": "M10",
            "section": "main",
            "title": "Reward structure",
            "status": "draft",
            "bullets": [
                "Distance band: credit only when target visible inside operational range.",
                "Capture term: quality × coverage × (1 − cloud_frac) at budgeted shutter events.",
                "Penalties: shutter waste, torque / wheel-energy effort, repeat-target novelty loss.",
            ],
            "notes": "User choice: reward breakdown (slide 10-B). Source: machine-learning.md.",
        },
        {
            "id": "M11",
            "section": "main",
            "title": "Satellite setup",
            "status": "draft",
            "bullets": [
                "Bus: 250 kg; 2D env uses Izz = 31.2 kg·m²; reaction-wheel torque limits.",
                "Primary camera: 9344×7000 px, 3.2 µm pitch, 1067 mm focal length; ray-traced clouds.",
                "Dual-camera sensing: primary observation line (100 bins) + secondary context.",
            ],
            "notes": "User: mix platform + diagram + constants. Add subsystem diagram in PPT.",
        },
        {
            "id": "M12",
            "section": "main",
            "title": "Safety — AttitudeSafetyController",
            "status": "draft",
            "bullets": [
                "Torque path: agent τ_cmd → arbitrate() → reaction wheel (45° off-nadir hard limit).",
                "Normal: pass-through; near envelope: tapered torque; violation predicted → safe mode.",
                "Safe mode: ignore agent; sequence BRAKE → CRUISE → SETTLE → LOCKOUT → nadir recovery.",
            ],
            "notes": "Source: simulation/attitude_controller.py::AttitudeSafetyController.",
        },
        {
            "id": "M13",
            "section": "main",
            "title": "Experiment methodology",
            "status": "draft",
            "bullets": [
                "Hypothesis-driven pipeline: charter → literature → design → run → verdict card.",
                "One logical delta per arm; frozen protocol (dt, seeds, episode counts).",
                "Invalid runs documented and excluded from verdicts.",
            ],
            "notes": "User choice: pipeline methodology (slide 13-A).",
        },
        {
            "id": "M14",
            "section": "main",
            "title": "Experiment campaign timeline",
            "status": "draft",
            "bullets": [
                "Exp 1 — Shutter threshold (MPO): H1 not supported.",
                "Exp 2 — Modular encoder (SAC): H1 not supported; deferred interest.",
                "Exp 3 — SAC vs MPO compare · Exp 4 — Agent-reference pointing (vector OBC).",
            ],
            "notes": "User choice: timeline (slide 14-A).",
        },
        {
            "id": "M15",
            "section": "main",
            "title": "Early experiments — lessons from negative results",
            "status": "draft",
            "bullets": [
                "Exp 1: raising shutter threshold 0.5→0.9 did not stop spam (~515 cmds/ep).",
                "Exp 2: flat vs compress-k=8 encoder — no KPI win; learning_mode false both arms.",
                "Shaped later work: dense MPO credit, dt profile fixes, focus on learnability first.",
            ],
            "notes": "User choice: combined Exp1+2 (slide 15-C).",
        },
        {
            "id": "M16",
            "section": "main",
            "title": "Exp 4 — Agent-reference pointing (vector OBC)",
            "status": "draft",
            "bullets": [
                "Ref0 (torque): agent commands wheel torque directly + AttitudeSafetyController.",
                "Ref1 (vector): dim0 = u ∈ [-1,1] → off-nadir offset → θ_req → PD → τ.",
                "Hypothesis H4: vector mode improves learning vs torque with fewer safe-mode takeovers.",
            ],
            "notes": "User choice: Exp4 only on main path (slide 16-B). Exp3 in backup.",
        },
        {
            "id": "M17",
            "section": "main",
            "title": "Results — behavioral evidence (video)",
            "status": "draft",
            "bullets": [
                "Baseline nb07: blind shuttering on all target vectors.",
                "Trained policy: [insert eval MP4 path / frame stills after export].",
                "Look for: cloud avoidance, capture timing, pointing for quality.",
            ],
            "notes": "Embed video or stills. Paths under backend/autonomous_control/runs/*/episodes/",
        },
        {
            "id": "M18",
            "section": "main",
            "title": "Results — learning curves",
            "status": "draft",
            "bullets": [
                "Train / eval return trends: plots/learning_curves.png per run.",
                "Early abort / patience stops documented when plateau.",
                "[Insert best overnight / compare_sac / compare_mpo plots when frozen].",
            ],
            "notes": "User: expand results across multiple slides.",
        },
        {
            "id": "M19",
            "section": "main",
            "title": "Results — KPI summary",
            "status": "draft",
            "bullets": [
                "learning_mode, eval mean return, shutter cmds/ep, safe_mode_takeover_count.",
                "Qualitative headline for now — quantitative superiority vs nb07 deferred to final eval.",
                "summary_metrics.json + episodes.csv per run folder.",
            ],
            "notes": "",
        },
        {
            "id": "M20",
            "section": "main",
            "title": "Conclusion",
            "status": "draft",
            "bullets": [
                "Hypothesis partially tested: cloud-aware pipeline and training loop are in place.",
                "Negative results (Exp 1–2) narrowed the search space for reward and architecture.",
                "Superiority over deterministic baseline not yet proven with final matched eval numbers.",
            ],
            "notes": "User choice: partially tested (slide 18-B).",
        },
        {
            "id": "M21",
            "section": "main",
            "title": "Further research & next steps",
            "status": "draft",
            "bullets": [
                "Continue experimentation until learned policy beats nb07 on matched episodes.",
                "Physically plausible, correct learning method not yet found — iterate reward + control interface.",
                "Promote vector OBC if H4 supported; then mission-planner layer over OBC.",
            ],
            "notes": "User wording: iterate until beat baseline.",
        },
        {
            "id": "M22",
            "section": "main",
            "title": "Thank you",
            "status": "ready",
            "bullets": [
                "Questions?",
                "Cédric Grieder · ETH × Beyond Gravity semester project",
            ],
            "notes": "",
        },
        {
            "id": "A01",
            "section": "admin",
            "title": "Admin slide 1",
            "status": "placeholder",
            "bullets": [
                "Company / org content — add branding, context, or intro from Beyond Gravity.",
            ],
            "notes": "User fills in.",
        },
        {
            "id": "A02",
            "section": "admin",
            "title": "Admin slide 2",
            "status": "placeholder",
            "bullets": [
                "Second admin slide — team, project placement, or logistics.",
            ],
            "notes": "User fills in.",
        },
        {
            "id": "B01",
            "section": "backup",
            "title": "Backup — video gallery (eval runs)",
            "status": "placeholder",
            "bullets": [
                "ml_overnight_h1a_mpo_sparse — eval_best_reward.mp4",
                "ml_overnight_h1a_mpo_sparse — train_last_reward.mp4",
                "[Add more run folders from backend/autonomous_control/runs/]",
            ],
            "notes": "Export paths when MP4s exist locally.",
        },
        {
            "id": "B02",
            "section": "backup",
            "title": "Backup — video gallery (baseline vs learned)",
            "status": "placeholder",
            "bullets": [
                "Notebook 07 baseline overflight export.",
                "Best eval checkpoint per algorithm arm.",
                "Frame manifests: .cursor/video_frame_inspect/data/",
            ],
            "notes": "",
        },
        {
            "id": "B03",
            "section": "backup",
            "title": "Backup — plots & diagnostics",
            "status": "placeholder",
            "bullets": [
                "returns_by_episode.png, episode reward/torque grids.",
                "Shutter cmds/ep distributions (Exp 1 arms).",
                "sim_timing / encoder ablation plots.",
            ],
            "notes": "",
        },
        {
            "id": "B04",
            "section": "backup",
            "title": "Backup — Exp 3 SAC vs MPO detail",
            "status": "draft",
            "bullets": [
                "H3: SAC sparse vs MPO dense at dt 1.5 s / 1.5 s.",
                "Claims: SAC learnable baseline; dense credit unblocks MPO.",
                "docs/experiments/pipeline/1-built/03-sac-mpo-compare.md",
            ],
            "notes": "",
        },
        {
            "id": "B05",
            "section": "backup",
            "title": "Backup — experiment × research cross-map",
            "status": "draft",
            "bullets": [
                "Each experiment ↔ hypothesis doc ↔ DECISIONS.md row ↔ investigation note.",
                "Example: Exp1 ↔ shutter-threshold-investigation.md ↔ D-009, D-010, D-011.",
                "Full index: docs/research/PROJECT_KNOWLEDGE.md layer 4–6.",
            ],
            "notes": "Shows breadth without cluttering main deck.",
        },
        {
            "id": "B06",
            "section": "backup",
            "title": "Backup — full experiment list & verdicts",
            "status": "draft",
            "bullets": [
                "Exp1 Shutter: not_supported · Exp2 Encoder: not_supported.",
                "Exp3 SAC/MPO: pending · Exp4 Vector OBC: pending.",
                "Supporting: sim_timing, movement constraints, cloud formation notebooks.",
            ],
            "notes": "Source: docs/ml/STATUS_2026-06.md",
        },
        {
            "id": "B07",
            "section": "backup",
            "title": "Backup — reward & environment constants",
            "status": "draft",
            "bullets": [
                "docs/presentation/machine-learning.md",
                "docs/presentation/environment-hyperparameters.md",
                "docs/presentation/technical-constants.md",
            ],
            "notes": "",
        },
        {
            "id": "B08",
            "section": "backup",
            "title": "Backup — literature & decisions log",
            "status": "draft",
            "bullets": [
                "docs/research/LITERATURE_HIGHLIGHTS.md",
                "docs/research/DECISIONS.md (D-002 dt, D-007 dense reward, D-013 video export, …)",
                "Hypothesis docs under backend/scripts/experiments/*/H*.md",
            ],
            "notes": "",
        },
    ],
}
